server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
        - id: book_route
          uri: http://localhost:8081/products/**
          predicates:
            - Path=/products/**
        - id: profile_route
          uri: http://localhost:8082/profiles/**
          predicates:
            - Path=/profiles/**
        - id: order_route
          uri: http://localhost:8084/orders/**
          predicates:
            - Path=/orders/**
        - id: payment_route
          uri: http://localhost:8083/payments/**
          predicates:
            - Path=/payments/**