server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product_route
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: profile_route
          uri: lb://profile-service
          predicates:
            - Path=/profiles/**
        - id: order_route
          uri: http://localhost:8084/orders/**
          predicates:
            - Path=/orders/**
        - id: payment_route
          uri: http://localhost:8083/payments/**
          predicates:
            - Path=/payments/**