server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

properties:
  mark: payment-service

sentry:
  dsn: "not found yet"
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0