server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

properties:
  mark: product-service

sentry:
  dsn: $PRODUCT_URI
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0