server:
  port: 8082

properties:
  mark: profile-service

cache:
  cron:
    profile:
      clear: "0 */5 * ? * *"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE