# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Common pipeline for all services

on:
  push:
    branches: [
      "config-service",
      "gateway-service",
      "discovery-service",
      "order-service",
      "payment-service",
      "profile-service",
      "product-service"
    ]
  pull_request:
    branches: [
      "config-service",
      "gateway-service",
      "discovery-service",
      "order-service",
      "payment-service",
      "profile-service",
      "product-service"
    ]
    

jobs:
  build-config-service:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/config-service'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build config-service artifact
      run: mvn -pl config-service clean install
  deploy-config-service:
    runs-on: ubuntu-latest
    needs: build-config-service
    if: github.ref == 'refs/heads/config-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy config service"

  build-gateway-service:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/gateway-service'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build gateway-service artifact
        run: mvn -pl gateway-service clean install
  deploy-gateway-service:
    runs-on: ubuntu-latest
    needs: build-gateway-service
    if: github.ref == 'refs/heads/gateway-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy gateway service"

  build-discovery-service:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/discovery-service'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build gateway-service artifact
        run: mvn -pl gateway-service clean install
  deploy-discovery-service:
    runs-on: ubuntu-latest
    needs: build-discovery-service
    if: github.ref == 'refs/heads/config-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy discovery service"

  build-order-service:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/order-service'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build order-service artifact
        run: mvn -pl order-service clean install -Dmaven.test.skip=true
      - name: Check
        run: ls -all
      - name: Deploy app
        run: cd order-service/deploy &&
          docker build  -t ${{ secrets.DOCKER_HUB_LOGIN }}/order-service:latest -f- ./ < Dockerfile &&
          docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_PASSWORD }} &&
          docker push ${{ secrets.DOCKER_HUB_LOGIN }}/order-service:latest
  deploy-order-service:
    runs-on: ubuntu-latest
    needs: build-order-service
    if: github.ref == 'refs/heads/order-service'
    steps:
      - name: Check
        run: ls -all

  build-profile-service:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/profile-service'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build profile-service artifact
        run: mvn -pl profile-service clean install -Dmaven.test.skip=true
  deploy-profile-service:
    runs-on: ubuntu-latest
    needs: build-profile-service
    if: github.ref == 'refs/heads/profile-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy profile service"

  build-payment-service:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/payment-service'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build payment-service artifact
        run: mvn -pl payment-service clean install -Dmaven.test.skip=true
  deploy-payment-service:
    runs-on: ubuntu-latest
    needs: build-payment-service
    if: github.ref == 'refs/heads/payment-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy payment service"

  build-product-service:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/product-service'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build product-service artifact
        run: mvn -pl product-service clean install -Dmaven.test.skip=true
  deploy-product-service:
    runs-on: ubuntu-latest
    needs: build-product-service
    if: github.ref == 'refs/heads/product-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy product service"
