# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Common pipeline for all services

on:
  push:
    branches: [
      "config-service",
      "gateway-service",
      "order-service",
      "payment-service",
      "profile-service",
      "product-service"
    ]
  pull_request:
    branches: [
      "config-service",
      "gateway-service",
      "order-service",
      "payment-service",
      "profile-service",
      "product-service"
    ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build all artifacts
      run: mvn -B clean install -Dmaven.test.skip=true
  deploy-config-service:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/config-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy config service"
  deploy-gateway-service:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/gateway-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy gateway service"
  deploy-order-service:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/order-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy order service"
  deploy-profile-service:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/profile-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy profile service"
  deploy-payment-service:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/payment-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy payment service"
  deploy-product-service:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/product-service'
    steps:
      - name: Deploy app
        run: echo "Start deploy product service"
